# Generated by Django 3.0.3 on 2021-04-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPdf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PdfName', models.CharField(default=None, max_length=50)),
                ('Filename', models.CharField(default=None, max_length=50)),
                ('UserId', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'Pdf_Details',
            },
        ),
    ]
