# Generated by Django 3.0.3 on 2021-04-17 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppPdf', '0002_pdf_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf_details',
            name='Filename',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='pdf_details',
            name='PdfName',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
